### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by ericoporto** [ericoporto/mode7#1]
We probably want to refactor this more so we can separate the behaviors

### ~~TO-DO:~~

-  we probably want to have a transform world phase that updates the position of everything and a render phase that actually does the drawing

Picked out some items in their own issues to deal with later. This last remaining item I don't want to do right now.

### DONE:

- [x] the affine transform or at least the ground rendering should be refactored to be the core of the module, probably the part named mode7
- [x] the full world manipulation will probably be refactored to a mode7world struct
- [x] object rendering (the billboard sprites) should be moved out of the module, but it should be pretty obvious how to do it (this would enable in the future people using Overlays once they can be resized somehow, but also objects and characters right now if simple click interaction is desired)
- [x] original kart aspects of the module should be moved out, while the module has to keep mechanisms to implement the rendering parts of it

![ship_really_small](https://user-images.githubusercontent.com/2244442/160260167-0f6ab7a0-fd55-472a-839f-5332f3970476.gif)

**Comment by ericoporto** [comment]
ok, there's more things I would like to do but it's better to release something soon and workout things later on. I want to instead focus on additional room examples with different usages and then put this on the forums to see how it goes.
